"""changed released_date to release_date

Revision ID: 98d0e64cf324
Revises: e73b9542161e
Create Date: 2026-02-12 15:18:49.194755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d0e64cf324'
down_revision: Union[str, Sequence[str], None] = 'e73b9542161e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_date', sa.Date(), nullable=True))
    op.drop_column('movies', 'released_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('released_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('movies', 'release_date')
    # ### end Alembic commands ###
