"""added check constraint check_production_cost_positive

Revision ID: a957dd88732d
Revises: e1bad132928d
Create Date: 2026-02-12 20:18:25.858194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a957dd88732d'
down_revision: Union[str, Sequence[str], None] = 'e1bad132928d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "check_production_cost_positive",  # must match model name ideally
        "movies",
        "production_cost >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "check_production_cost_positive",
        "movies",
        type_="check",
    )
    # ### end Alembic commands ###
