"""Add on delete cascade constraint to cast table

Revision ID: be3ea984b70c
Revises: 8932de836010
Create Date: 2026-02-17 19:16:03.715686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3ea984b70c'
down_revision: Union[str, Sequence[str], None] = '8932de836010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('movie_cast_movie_id_fkey'), 'movie_cast', type_='foreignkey')
    op.drop_constraint(op.f('movie_cast_actor_id_fkey'), 'movie_cast', type_='foreignkey')
    op.create_foreign_key(None, 'movie_cast', 'actors', ['actor_id'], ['actor_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movie_cast', 'movies', ['movie_id'], ['movie_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_cast', type_='foreignkey')
    op.drop_constraint(None, 'movie_cast', type_='foreignkey')
    op.create_foreign_key(op.f('movie_cast_actor_id_fkey'), 'movie_cast', 'actors', ['actor_id'], ['actor_id'])
    op.create_foreign_key(op.f('movie_cast_movie_id_fkey'), 'movie_cast', 'movies', ['movie_id'], ['movie_id'])
    # ### end Alembic commands ###
