"""Added production_cost and revenue columns to movie table

Revision ID: e1bad132928d
Revises: d6e66c906c95
Create Date: 2026-02-12 19:41:23.212339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bad132928d'
down_revision: Union[str, Sequence[str], None] = 'd6e66c906c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('production_cost', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('revenue', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'revenue')
    op.drop_column('movies', 'production_cost')
    # ### end Alembic commands ###
