"""init

Revision ID: e73b9542161e
Revises: 
Create Date: 2026-02-12 15:06:25.830317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73b9542161e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('actor_id')
    )
    op.create_table('studios',
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('studio_id')
    )
    op.create_table('movies',
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('released_date', sa.Date(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=True),
    sa.Column('sequel_to_movie_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['sequel_to_movie_id'], ['movies.movie_id'], ),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.studio_id'], ),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('movie_cast',
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('role_type', sa.String(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=False),
    sa.Column('billing_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('movie_cast')
    op.drop_table('movies')
    op.drop_table('studios')
    op.drop_table('actors')
    # ### end Alembic commands ###
