from typing import Protocol
from src.domain.Actor import Actor

class ActorRepositoryProtocol(Protocol):
    def add_actor(self, actor:Actor):
        ...
    def get_all_actors(self) -> list[Actor]:
        ...
    def get_actor_by_name(self,query:str):
        ...
    def remove_actor(self,actor:Actor):
        ...
    def update_actor(self,actor:Actor):
        ...