from typing import Protocol
from src.domain.cast import Cast

class CastRepositoryProtocol(Protocol):
    def add_cast(self, cast:Cast):
        ...
    def get_all_casts(self) -> list[Cast]:
        ...
    def get_specific_cast(self,movie_id:str,actor_id:str)->Cast:
        ...
    def get_cast_by_movie(self,movie_id:str):
        ...
    def remove_cast(self,movie_id:str,actor_id:str):
        ...
    def update_cast(self,cast:Cast):
        ...