from typing import Protocol
from src.domain.cast import Cast
from src.domain.actor import Actor

class CastRepositoryProtocol(Protocol):
    def add_cast(self, cast:Cast):
        ...
    def get_all_casts(self) -> list[Cast]:
        ...
    def get_specific_cast(self,movie_id:str,actor_id:str)->Cast:
        ...
    def get_cast_by_movie(self,movie_id:str) -> list[tuple[Cast, Actor]]:
        ...
    def remove_cast(self,movie_id:str,actor_id:str):
        ...
    def update_cast(self,cast:Cast):
        ...
    def add_seed_records(self, casts: list[Cast]) -> None:
        ...