from typing import Protocol

from src.domain.movie import Movie

class MovieRepositoryProtocol(Protocol):
    def add_movie(self, movie: Movie) -> str:
        ...
    def get_all_movies(self) -> list[Movie]:
        ...
    def find_movies_by_title(self, query:str) -> list[Movie]:
        ...
    def remove_movie(self, movie_id: str) -> None:
        ...
    def update_movie(self, movie: Movie) -> None:
        ...
    def get_movie_by_id(self, movie_id: str) -> Movie | None: 
        ...
    def add_seed_records(self, movies: list[Movie]) -> None:
        ... 