from typing import Protocol
from src.domain.Studio import Studio

class StudioRepositoryProtocol(Protocol):
    def add_actor(self, studio:Studio):
        ...
    def get_all_actors(self) -> list[Studio]:
        ...
    def get_actor_by_name(self,query:str):
        ...
    def remove_actor_by_id(self,actor_id:str):
        ...
    def update_actor(self,actor_id:str,studio:Studio):
        ...