from typing import Protocol
from src.domain.Studio import Studio

class StudioRepositoryProtocol(Protocol):
    def add_studio(self, studio:Studio):
        ...
    def get_all_studios(self) -> list[Studio]:
        ...
    def get_studio_by_name(self,query:str):
        ...
    def remove_studio_by_id(self,studio_id:str):
        ...
    def update_studio(self,studio_id:str,studio:Studio):
        ...